feat: 96/abort session and clear steps
elastic/synthetics-recorder pull request #105
Opened 2021-12-03 15:22 UTC by justinkambic

This is a reposting of https://github.com/elastic/synthetics-recorder/pull/97; after we brought this repo public my fork lost association with open PRs and new commits would not show up/trigger the CI process.

After numerous attempts to re-establish the connection I opted to simply re-open a new PR. Description and previous comments available at the link above.

2021-12-03 16:05 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-105/detail/PR-105/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-105/detail/PR-105/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-105/detail/PR-105/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-105/detail/PR-105/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics-recorder_105.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2021-12-03T15:12:34.515Z&rangeTo=2021-12-03T15:32:34.515Z&transactionName=apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=9d731c2b14322d3eb8737736d0e00ede&transactionId=9874ccccb517133f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-03T15:22:34.515+0000


* Duration: 43 min 57 sec


* Commit: 60c42e7c449c5e3aaccfef41f20468dc12c6a536



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 31  |
| Skipped      | 0 |
| Total        | 31   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-03 23:47 UTC, vigneshshanmugam requested changes
I am confused with some of the changes in this PR.

1. Start over does not create a new browser session.
2. I can create endless no of browser sessions with Start recording and Start over. Previous browser sessions are not closed properly.
3. Previous actions are still showing up even if I start over.

2021-12-06 17:12 UTC, justinkambic commented
@vigneshshanmugam sorry, I should've run this branch before re-opening the PR. The functionality is not working the way it was when I last developed on this branch, I will ping you when it's ready for review.

2021-12-06 20:04 UTC, justinkambic commented
@vigneshshanmugam I think this is now working as the design expects.

2021-12-09 00:05 UTC, vigneshshanmugam approved these changes
LGTM pending a small change.

2021-12-09 13:50 UTC, justinkambic commented on src/components/Header.tsx
> +            iconType={isRecording ? "pause" : "play"}
I'm happy to do that, sure!

2021-12-09 13:50 UTC, justinkambic commented on package.json
> +    "nodemon": "^2.0.15",
must be, will debug.

2021-12-09 13:51 UTC, justinkambic commented on package.json
> +    "nodemon": "^2.0.15",
sorry that you've run into several of these recently.

2021-12-09 13:58 UTC, justinkambic commented on package.json
> +    "nodemon": "^2.0.15",
FYI a rebase of latest `main` seems to have cleaned up that diff.

2021-12-09 17:01 UTC, justinkambic commented on src/components/Header.tsx
> +            iconType={isRecording ? "pause" : "play"}
I've added an `enum` implementation here: https://github.com/elastic/synthetics-recorder/pull/105/commits/2349d6fe85b861a6aeabf52c1f2d1e204335f6ba

LMK if that is ok to you.

2021-12-10 00:42 UTC, vigneshshanmugam commented on src/components/Header.tsx
> +            iconType={isRecording ? "pause" : "play"}
Yes looks good, thanks 👍🏽

2021-12-10 00:42 UTC, vigneshshanmugam approved these changes

2021-12-13 15:09 UTC, merged