feat: Add tooltip to assertion element heading
elastic/synthetics-recorder pull request #160
Opened 2022-02-16 20:41 UTC by justinkambic

## Summary

Resolves #65.

Adds a tooltip to the assertion element's heading per the designs.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/18429259/154353559-cc1a60fd-3bfd-47a6-831f-a45eebc3e2a5.png">

## Implementation details

Note: it does not include a link as the design indicates. I'm not sure what location that link should go to, and the tooltip's default behavior is to collapse when the mouse is no longer hover on the child element.

We can modify this implementation by fleshing out this requirement more.

## How to validate this change

Record steps, insert an assertion, edit it and see the tooltip appear over the icon.

2022-02-16 21:00 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-160/detail/PR-160/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-160/detail/PR-160/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-160/detail/PR-160/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-160/detail/PR-160/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics-recorder_160.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-02-16T20:31:59.407Z&rangeTo=2022-02-16T20:51:59.407Z&transactionName=apm-agent-rum/synthetics-recorder-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=b60be71466a5ac2a1e1d6a13606fea78&transactionId=2d8ab4ab95c0fe74)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-02-16T20:41:59.407+0000


* Duration: 18 min 14 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 94  |
| Skipped      | 0 |
| Total        | 94   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-16 22:10 UTC, vigneshshanmugam approved these changes

2022-02-17 14:28 UTC, lucasfcosta approved these changes
LGTM, also validated E2E 🙌

2022-02-17 15:59 UTC, liciavale requested changes
I had a chat with Justin about this and I think we need to replace the tooltip.
It should not be a tooltip but a popover and we should add the link that links to the [playwright doc ](https://playwright.dev/docs/assertions/) in case users want to learn more. 
Sorry to push this back.

2022-02-23 17:58 UTC, justinkambic commented
@liciavale can you comment on this implementation from a design perspective and let me know if there's anything you'd like to see adjusted?

 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/18429259/155378746-558e5246-6b24-4c1a-8404-0dcecc7504e8.png">


Thanks for catching the incorrect element.

2022-03-24 19:21 UTC, justinkambic commented
@liciavale see this updated screenshot:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/18429259/159994158-2da52d61-975d-4950-98bd-7ad40f01a7e6.png">

2022-03-28 08:39 UTC, liciavale approved these changes

2022-03-28 13:23 UTC, merged