fix: Show label as tooltip when the viewport width is small
elastic/synthetics-recorder pull request #170
Opened 2022-03-15 21:13 UTC by kyungeunni

## Summary

closes #163 

When the recorder's viewport width is smaller than a certain size, the buttons hide the label and only show the icon. This PR adds a tooltip to the buttons when the label is disappeared due to mentioned reason.

Although there are some things to be clairfied before merging this PR:
- [ ]  Some of the buttons [already have tooltip](https://github.com/elastic/synthetics-recorder/issues/163#issuecomment-1067846533). Should the label take presendence over the description? or do we merge those two contents into a tooltip?
- [ ] If we were to display descriptions for the buttons, revisit the wordings.

2022-03-15 21:25 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-170/detail/PR-170/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-170/detail/PR-170/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-170/detail/PR-170/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-170/detail/PR-170/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics-recorder_170.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-03-15T21:03:53.633Z&rangeTo=2022-03-15T21:23:53.633Z&transactionName=apm-agent-rum/synthetics-recorder-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=f8358652c6cd7905728dc6fe69c1b6b0&transactionId=3fca2ea7c5b2a6a6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-15T21:13:53.633+0000


* Duration: 12 min 49 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 94  |
| Skipped      | 0 |
| Total        | 94   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp%2FPR-170/detail/PR-170/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `run tests`
<ul>
<li>Took 0 min 19 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/synthetics-recorder-mbp/pipelines/PR-170/runs/1/steps/195/log/?start=0">here</a></li>
<li>Description: <code>/synthetics-recorder/.ci/scripts/run-test.sh</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-21 19:54 UTC, justinkambic requested changes
I'm seeing an issue where the fill and text content are not accounted for:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/18429259/159353256-85f50316-e7cb-46f1-b449-2102773bdfe0.png">

I've included some comments that should help resolve the problem.

2022-03-21 19:54 UTC, justinkambic commented on src/components/ControlButton.tsx
>      return (
```suggestion
    const { fill } = rest;
    return (
```

2022-03-28 16:55 UTC, kyungeunni commented on src/components/ControlButton.tsx
> +  const { children, fill, tooltipContent, ...rest } = props;
Thanks Justin. I've updated this!! I just learned that `EuiButtonIcon` expects the fill prop as `display=fill` whereas EuiButton expects `fill` as a standalone attribute. So I corrected it according to the expectations.

2022-03-28 16:58 UTC, kyungeunni commented on src/components/ControlButton.tsx
> +  const { children, fill, tooltipContent, ...rest } = props;
fixed [![Image from Gyazo](https://i.gyazo.com/9bbc34150afb3b6c138be390684ebcdb.gif)](https://gyazo.com/9bbc34150afb3b6c138be390684ebcdb)

2022-03-29 07:46 UTC, kyungeunni commented on src/components/ControlButton.tsx
>      return (
resolved by [5d747b6](https://github.com/elastic/synthetics-recorder/pull/170/commits/5d747b6840c610699b0e3f982bbbde504077868b)

2022-03-29 17:41 UTC, kyungeunni commented on src/components/ControlButton.tsx
> +  const { children, fill, tooltipContent, ...rest } = props;
Oh.. I think this is a outdated commit that you are looking at

2022-03-29 17:49 UTC, justinkambic commented on src/components/ControlButton.tsx
> +  const { children, fill, tooltipContent, ...rest } = props;
It's an outdated comment actually - I think it was somehow included from my previous review and nested under my approval review. You can safely ignore it!

2022-03-29 18:06 UTC, merged